name: Deploy to one.com via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 compatibility

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          ftp-server: "ftp://${{ secrets.FTP_HOST }}"  # Example: ftp://ftp.yourdomain.com
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Directory to upload
          server-dir: "/webroots/a05056f"  # Remote directory on server
          method: "ftp"  # Specifies FTP method
          debug: true
