name: Deploy to one.com via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*"
          target: "/webroots/a05056f"
          method: sftp  # Specify SFTP method
          debug: true
          timeout: "120s"  
